version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
<<<<<<< HEAD
<<<<<<< HEAD
    
=======
=======
>>>>>>> origin/localbranch

networks:
  default:
    external:
      name: agronetwork
<<<<<<< HEAD
>>>>>>> origin/9-correct
=======
>>>>>>> origin/localbranch
