version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/app
      - /app/node_modules
<<<<<<< HEAD
    
=======

networks:
  default:
    external:
      name: agronetwork
>>>>>>> origin/9-correct
